USE RENTING;
SELECT * FROM `full` LIMIT 100;
SELECT COUNT(*) FROM `full`;
SELECT `company`, COUNT(*) AS `count_company` FROM `full` GROUP BY `company` ORDER BY `count_company` DESC;
SELECT `class`, COUNT(*) AS `count_class` FROM `full` GROUP BY `class` ORDER BY `count_class` DESC;
SELECT `province`, COUNT(*) AS `count_province` FROM `full` GROUP BY `province` ORDER BY `count_province` DESC;
SELECT `province`, `city`, COUNT(*) AS `count_city` FROM `full` GROUP BY `city` ORDER BY `count_city` DESC;
SELECT `province`, `city`, `district`, COUNT(*) AS `count_district` FROM `full` WHERE `district` != 'NULL' GROUP BY `district` ORDER BY `count_district` DESC LIMIT 30;
SELECT COUNT(*) FROM `full` WHERE `money` != 'NULL';
SELECT `money`, COUNT(*) AS `count_money` FROM `full` WHERE `money` != 'NULL' AND `money` != 'NOVA' GROUP BY `money` ORDER BY `count_money` DESC LIMIT 100;
SELECT COUNT(*) FROM `full` WHERE `room` != 'NULL';
SELECT `room`, COUNT(*) AS `count_room` FROM `full` WHERE `room` != 'NULL' GROUP BY `room` ORDER BY `count_room` DESC LIMIT 10;
SELECT COUNT(*) FROM `full` WHERE `area` != 'NULL';
SELECT `area`, COUNT(*) AS `count_area` FROM `full` WHERE `area` != 'NULL' GROUP BY `area` ORDER BY `count_area` DESC LIMIT 200;
SELECT ROUND(CONVERT(`area`, UNSIGNED)/10)*10 AS `num_area`, COUNT(*) AS `count_area` FROM `full` WHERE `area` != 'NULL' GROUP BY `num_area` HAVING `num_area`>0 AND `num_area`<300 ORDER BY `num_area`;
SELECT `direction`, COUNT(*) as `count_direction` FROM `full` WHERE `direction` != 'NULL' GROUP BY `direction` HAVING `count_direction`>10000 ORDER BY `count_direction` DESC;
SELECT COUNT(*) FROM `full` WHERE `floor` != 'NULL';
SELECT `floor`, COUNT(*) AS `count_floor` FROM `full` WHERE `floor` != 'NULL' GROUP BY `floor` ORDER BY `count_floor` DESC;
SELECT COUNT(*) FROM `full` WHERE `decoration` != 'NULL';
SELECT `decoration`, COUNT(*) AS `count_decoration` FROM `full` WHERE `decoration` != 'NULL' GROUP BY `decoration` ORDER BY `count_decoration` DESC;
SELECT COUNT(*) FROM `full` WHERE `old` != 'NULL';
SELECT ROUND(CONVERT(`old`, UNSIGNED)) AS `num_old`, COUNT(*) AS `count_old` FROM `full` WHERE `old` != 'NULL' GROUP BY `num_old` HAVING `num_old` < 2025 AND `num_old` >1900 ORDER BY `num_old` DESC;
SELECT * FROM `full` WHERE `old` LIKE '%1936%';