USE RENTING;
SELECT * FROM `full` LIMIT 100;
SELECT COUNT(*) FROM `full`;
SELECT `company`, COUNT(*) AS `count_company` FROM `full` GROUP BY `company` ORDER BY `count_company` DESC;
SELECT `class`, COUNT(*) AS `count_class` FROM `full` GROUP BY `class` ORDER BY `count_class` DESC;
SELECT `province`, COUNT(*) AS `count_province` FROM `full` GROUP BY `province` ORDER BY `count_province` DESC;
SELECT `province`, `city`, COUNT(*) AS `count_city` FROM `full` GROUP BY `city` ORDER BY `count_city` DESC;
SELECT * FROM `full` WHERE `district` = 'NULL';
SELECT `province`, `city`, `district`, COUNT(*) AS `count_district` FROM `full` WHERE `district` != 'NULL' GROUP BY `district` ORDER BY `count_district` DESC LIMIT 30;
SELECT COUNT(*) FROM `full` WHERE `money` != 'NULL';
SELECT * FROM `full` WHERE `class` = '出租房' AND `money` = 'NULL';
SELECT ROUND(CONVERT(`money`, UNSIGNED)/1000)*1000 AS `num_money`, COUNT(*) AS `count_money` FROM `full` WHERE `money` != 'NULL' GROUP BY `num_money` HAVING `num_money`<100000 ORDER BY `num_money` ASC;
SELECT ROUND(CONVERT(`money`, UNSIGNED)/1000)*1000 AS `num_money`, COUNT(*) AS `count_money` FROM `full` WHERE `class` = '出租房' AND `money` != 'NULL' GROUP BY `num_money` HAVING `num_money`<100000 ORDER BY `num_money` ASC;
SELECT ROUND(CONVERT(`money`, UNSIGNED)/1000)*1000 AS `num_money`, COUNT(*) AS `count_money` FROM `full` WHERE `class` = '商铺出租房' AND `money` != 'NULL' GROUP BY `num_money` HAVING `num_money`<100000 ORDER BY `num_money` ASC;
SELECT ROUND(CONVERT(`money`, UNSIGNED)/1000)*1000 AS `num_money`, COUNT(*) AS `count_money` FROM `full` WHERE `class` = '写字楼出租房' AND `money` != 'NULL' GROUP BY `num_money` HAVING `num_money`<100000 ORDER BY `num_money` ASC;
SELECT COUNT(*) FROM `full` WHERE `room` != 'NULL';
SELECT `room`, COUNT(*) AS `count_room` FROM `full` WHERE `room` != 'NULL' GROUP BY `room` ORDER BY `count_room` DESC LIMIT 10;
SELECT COUNT(*) FROM `full` WHERE `area` != 'NULL';
SELECT ROUND(CONVERT(`area`, UNSIGNED)/10)*10 AS `num_area`, COUNT(*) AS `count_area` FROM `full` WHERE `area` != 'NULL' GROUP BY `num_area` HAVING `num_area`>0 AND `num_area`<300 ORDER BY `num_area`;
SELECT ROUND(CONVERT(`area`, UNSIGNED)/10)*10 AS `num_area`, COUNT(*) AS `count_area` FROM `full` WHERE `class` = '出租房' AND `area` != 'NULL' GROUP BY `num_area` HAVING `num_area`>0 AND `num_area`<300 ORDER BY `num_area`;
SELECT ROUND(CONVERT(`area`, UNSIGNED)/10)*10 AS `num_area`, COUNT(*) AS `count_area` FROM `full` WHERE `class` = '商铺出租房' AND `area` != 'NULL' GROUP BY `num_area` HAVING `num_area`>0 AND `num_area`<500 ORDER BY `num_area`;
SELECT ROUND(CONVERT(`area`, UNSIGNED)/10)*10 AS `num_area`, COUNT(*) AS `count_area` FROM `full` WHERE `class` = '写字楼出租房' AND `area` != 'NULL' GROUP BY `num_area` HAVING `num_area`>0 AND `num_area`<500 ORDER BY `num_area`;
SELECT `direction`, COUNT(*) as `count_direction` FROM `full` WHERE `direction` != 'NULL' GROUP BY `direction` ORDER BY `count_direction` DESC;
SELECT COUNT(*) FROM `full` WHERE `floor` != 'NULL';
SELECT `floor`, COUNT(*) AS `count_floor` FROM `full` WHERE `floor` != 'NULL' GROUP BY `floor` ORDER BY `count_floor` DESC;
SELECT COUNT(*) FROM `full` WHERE `decoration` != 'NULL';
SELECT `decoration`, COUNT(*) AS `count_decoration` FROM `full` WHERE `decoration` != 'NULL' GROUP BY `decoration` ORDER BY `count_decoration` DESC;
SELECT COUNT(*) FROM `full` WHERE `old` != 'NULL';
SELECT ROUND(CONVERT(`old`, UNSIGNED)) AS `num_old`, COUNT(*) AS `count_old` FROM `full` WHERE `old` != 'NULL' GROUP BY `num_old` HAVING `num_old` < 2025 AND `num_old` >1950 ORDER BY `num_old` DESC;

SELECT COUNT(*) FROM `full` WHERE `money` != 'NULL' AND `community` != 'NULL' AND `floor` != 'NULL';
SELECT COUNT(*) FROM `full` WHERE `money` != 'NULL' AND `community` != 'NULL' AND `area` != 'NULL';
SELECT COUNT(*) FROM `full` WHERE `money` != 'NULL' AND `community` != 'NULL' AND `floor` != 'NULL' AND `area` != 'NULL';
SELECT *, COUNT(*) AS `count_repeat` FROM `full` WHERE `money` != 'NULL' AND `community` != 'NULL' AND `floor` != 'NULL' AND `area` != 'NULL' GROUP BY `community`, `money`, `floor`, `area` ORDER BY `count_repeat` DESC;

SELECT * FROM `full` WHERE `date` = '2018-01-02' AND `community` = '五矿崇文金城';
SELECT * FROM `full` WHERE `community` = '尹东新村六期' AND `money` = '1460' AND `floor` = '4/18';
SELECT * FROM `full` WHERE `district` = '九龙坡' AND `community` = '华宇老街印象';